#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX
// NodeMCU safe audio pins
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_25
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_26
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_27

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_13
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_12
#endif

#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define ASR_BUTTON_GPIO         GPIO_NUM_NC
#define BUILTIN_LED_GPIO        GPIO_NUM_2

#define ML307_RX_PIN            GPIO_NUM_NC
#define ML307_TX_PIN            GPIO_NUM_NC

// NodeMCU standard I2C pins
#define DISPLAY_SDA_PIN         GPIO_NUM_21
#define DISPLAY_SCL_PIN         GPIO_NUM_22
#define DISPLAY_WIDTH           128

#if CONFIG_OLED_SSD1306_128X32
#define DISPLAY_HEIGHT  32
#elif CONFIG_OLED_SSD1306_128X64 || CONFIG_OLED_SH1106_128X64
#define DISPLAY_HEIGHT  64
#else
#define DISPLAY_HEIGHT  64
#endif

#define DISPLAY_MIRROR_X        false
#define DISPLAY_MIRROR_Y        false

#define LAMP_GPIO               GPIO_NUM_NC

#endif // _BOARD_CONFIG_H_
